MOVIE/MOVIE/movie/film/urls.py
from os import path

from django.conf import settings
from django.conf.urls.static import static

from django.urls import path
from . import views

app_name = 'film'

urlpatterns = [
    #path('', views.home, name="home"),
    path('',views.MovieList.as_view(),name="home"),

    #path('addmovie', views.addmovie, name="addmovie"),
    path('addmovie',views.Movieadd.as_view(),name="addmovie"),


    path('movie/<int:pk>',views.MovieDetail.as_view(),name='detail'),

    #path('moviedetails/<int:p>/', views.moviedetails, name='moviedetails'),
    path('m/<int:pk>',views.MovieDetail.as_view(),name='moviedetails'),

    path('movieedit/<int:p>', views.movieedit, name="movieedit"),

    path('deletemovie/<int:p>', views.deletemovie, name="deletemovie"),
    # path('delete/<int:pk>',views.Moviedelete.as_view(),name='delete'),

]





MOVIE/MOVIE/movie/movie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('film.urls')),]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MOVIE/MOVIE/movie/film/models.py
from django.db import models


# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=20)
    desc = models.CharField(max_length=300)
    year = models.IntegerField(default=0)
    image = models.ImageField(upload_to="film/image",null=True,blank=True)

    def __str__(self):
        return self.title


MOVIE/MOVIE/movie/film/forms.py


from django import forms
from .models import Movie

class Movieform(forms.ModelForm):
    class Meta:
        model = Movie
        fields = "__all__"

MOVIE/MOVIE/movie/film/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import render
from .models import Movie
from .forms import Movieform
from django.views.generic import ListView, DetailView,CreateView,DeleteView
from django.urls import reverse_lazy

# Create your views here.


#def home(request):
#    k = Movie.objects.all()
#    return render(request, "home.html", {'m': k})

class MovieList(ListView):  #displays all objects/records retieving from a model
    model=Movie
    template_name="home.html"
    context_object_name="m"

# def addmovie(request):
#     if (request.method == "POST"):
#         t = request.POST['t']
#         d = request.POST['d']
#         y = request.POST['y']
#         i = request.FILES['i']
#         m = Movie.objects.create(title=t, desc=d, year=y , image=i)
#         m.save()
#         return home(request)
#     return render(request, "addmovie.html" )

class Movieadd(CreateView):
    model=Movie
    template_name="addmovie.html"
    fields="__all__"
    success_url=reverse_lazy('film:home')



#def moviedetails(request, p):
#    d = Movie.objects.get(id=p)
#    return render(request, "moviedetails.html", {'d': d})

class MovieDetail(DetailView):
    model=Movie
    template_name="moviedetails.html"
    context_object_name="d"

# class Moviedelete(DetailView):
    # model=Movie
    # success_url=reverse_lazy('movieapp:index')
    # template_name='delete.html'

def movieedit(request, p):
    movie = get_object_or_404(Movie, id=p)

    if request.method == "POST":
        form = Movieform(request.POST, request.FILES, instance=movie)
        if form.is_valid():
            form.save()
            return render(request, "moviedetails.html", {'d': movie})
    else:
        form = Movieform(instance=movie)

    return render(request, "editmovie.html", {"form": form})


def deletemovie(request, p):
    movie = Movie.objects.get(id=p)
    movie.delete()
    return render(request,"home.html") # Redirect to the home page or any other desired page



MOVIE/MOVIE/movie/templates/addmovie.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!--  <center>-->
<!--    <form method="POST" enctype="multipart/form-data">-->
<!--      {% csrf_token %}-->
<!--      <h3 class="mt-4">Add Movie Details</h3>-->
<!--      <div class="mb-3">-->
<!--        <label class="form-label">TITLE</label>-->
<!--        <input type="text" class="form-control" name="t" placeholder="enter the title">-->
<!--      </div>-->
<!--      <div class="mb-3">-->
<!--        <label class="form-label">DESCRIPTION</label>-->
<!--        <input type="text" class="form-control" name="d" placeholder="enter description">-->
<!--      </div>-->
<!--      <div class="mb-3">-->
<!--        <label class="form-label">YEAR</label>-->
<!--        <input type="number" class="form-control" name="y" placeholder="enter year">-->
<!--      </div>-->
<!--      <div class="mb-3">-->
<!--        <label class="form-label">IMAGE</label>-->
<!--        <input type="file" class="form-control" name="i" >-->
<!--      </div>-->
<!--      <input type="submit" class="form-control" value="add movie">-->
<!--    </form>-->
<!--  </center>-->
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_table}}
  </table>
  <input type="submit">
</form>
{% endblock %}

MOVIE/MOVIE/movie/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title>Title</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>


<nav class="navbar navbar-expand-lg bg-body-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <a class="navbar-brand" href="#">Online Movie Store</a>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'film:home' %}">Home</a>
        </li>
      </ul>

    <a href="{% url 'film:addmovie' %}"  class="btn btn-primary">ADD MOVIE</a>
    </div>
  </div>
</nav>

{% block content %}

{% endblock %}

</body>
</html>

MOVIE/MOVIE/movie/templates/delete.html
{% extends 'base.html' %}
{% block body %}

<form method="post">
  {% csrf_token %}
  <p>are you sure you want to delete</p>
  <input type="submit">
</form>
{% endblock %}

MOVIE/MOVIE/movie/templates/editmovie.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <center>
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <h3 class="mt-4">Edit Movie Details</h3>
      {{ form.as_table }}
      <input type="submit" class="form-control" value="Update">
    </form>
  </center>
{% endblock %}

MOVIE/MOVIE/movie/templates/home.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<h2 class="mt-4">Welcome to Home page</h2></center>

        <!--CARD-->
{% for movie in m %}

<div class="card" style="width: 18rem;">
  <img src="{{ movie.image.url }}" height="250px" width="286px">
  <div class="card-body">
    <h5 class="card-title">{{ movie.title }}</h5>
    <p class="card-text">{{ movie.desc }}</p>
    <a href="{% url 'film:moviedetails' movie.id %}"  class="btn btn-primary">Details</a>  </div>
</div>

{% endfor %}

{% endblock %}

MOVIE/MOVIE/movie/templates/moviedetails.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<h2 class="mt-4"> Movie Details</h2></center>

        <!--CARD-->

<div class="card" style="width: 18rem;">
  <img src="{{ d.image.url }}" height="400px" width="350px">
</div>

<div class="moviedt">
    <h3>{{ d.title }}</h3>
    <p>{{ d.desc }}</p>
    <p>{{ d.year }}</p>
</div>

<center>
    <div>
<a href="{% url 'film:movieedit' p=d.id %}" class="btn btn-danger">Edit</a>
        <a href="{% url 'film:deletemovie' p=d.id %}" class="btn btn-danger">Delete</a>
    </div>
</center>




{% endblock %}